project:
  type: website
  resources: 
    - "CNAME"

website:
  title: "Jon Vanausdeln"
  favicon: "JRV-logo.png"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - text: About
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/jonvanausdeln
        target: _blank
      - icon: linkedin
        href: https://www.linkedin.com/in/jonvanausdeln/
        target: _blank
  open-graph: true

format:
  html:
    theme:
      - slate
      - brand
    css: styles.css
    toc: true

execute: 
  freeze: auto

