project:
  type: website
  resources: 
    - "CNAME"

website:
  title: "Jon Vanausdeln"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - about.qmd
  open-graph: true
  
format:
  html:
    theme:
      - cosmo
      - brand
    css: styles.css
    toc: true

execute: 
  freeze: auto

